# Generated by Django 3.2.2 on 2023-10-24 06:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps', '0002_auto_20231023_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='notesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('faculty', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('event_name', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('intro', models.TextField()),
                ('objective', models.TextField()),
                ('brief_desc', models.TextField()),
                ('reg_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brochure', models.ImageField(upload_to='brochures/')),
                ('channels', models.ManyToManyField(related_name='channels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
