# Generated by Django 3.2.2 on 2023-10-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_notesheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesheet',
            name='reg_fee',
            field=models.CharField(max_length=255),
        ),
    ]
