# Generated by Django 3.2.2 on 2023-10-24 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_notesheet_reg_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notesheet',
            name='brochure',
        ),
        migrations.RemoveField(
            model_name='notesheet',
            name='reg_fee',
        ),
    ]
