# Generated by Django 3.2.2 on 2023-10-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_auto_20231024_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesheet',
            name='reg_fee',
            field=models.CharField(default='NA', max_length=255),
        ),
    ]
