# Generated by Django 3.2.2 on 2023-10-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
