# Generated by Django 3.2.2 on 2023-11-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_alter_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_order',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
